signup/urls.py
from django.conf.urls import include, url
from base import views
from signup import settings
from . import admin as custom_admin

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.auth.models import User, Group
admin.autodiscover()
admin.site.unregister(Group)
admin.site.unregister(User)
admin.site.register(User, custom_admin.CustomUserAdmin)

handler403 = 'signup.errors.error403'
handler404 = 'signup.errors.error404'
handler500 = 'signup.errors.error500'

urlpatterns = (
    # Examples:
    # url(r'^$', 'signup.views.home', name='home'),
    # url(r'^signup/', include('signup.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^django-admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^admin/$', views.AdminDashboard.as_view(), name='admin-dash'),
    url(r'^admin/email/$', views.AdminSendEmailView.as_view(), name='admin-email'),
    url(r'^admin/reset/$', views.AdminCompetitionResetView.as_view(), name='admin-reset'),
    url(r'^admin/approvals/$', views.RedGreenApprovals.as_view(), name='admin-approvals'),
    url(r'^admin/approvals/(?P<participant_id>\d+)/approve', views.RedGreenApprove.as_view(), name='admin-approve'),
    url(r'^admin/approvals/(?P<participant_id>\d+)/unapprove', views.RedGreenUnapprove.as_view(), name='admin-unapprove'),

    url(r'^$', views.IndexView.as_view(), name='site-index'),
    url(r'^login/$', views.LoginView.as_view(), name='site-login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='site-logout'),

    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^signup/red/$', views.RedLanding.as_view(), name="red_signup"),
    url(r'^signup/red/real/$', views.RedSignup.as_view(), name='red_signup_real'),
    url(r'^signup/green/$', views.GreenSignup.as_view(), name="green_signup"),
    url(r'^forgot/$', views.ForgotPasswordView.as_view(), name='forgot-password'),

    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),

    url(r'^dashboard/check_in/$', views.CheckInView.as_view(), name='check-in'),
    url(r'^dashboard/join_team/$', views.TeamListView.as_view(), name='team-list'),
    url(r'^dashboard/join_team/(?P<team_id>[0-9-_:]+)/$', views.JoinTeamView.as_view(), name='join-team'),
    url(r'^dashboard/leave_team/$', views.LeaveTeamView.as_view(), name='leave-team'),
    url(r'^dashboard/request_captain/$', views.RequestCaptainView.as_view(), name='request-promotion'),
    url(r'^dashboard/step_down/$', views.StepDownView.as_view(), name='step-down'),
    url(r'^dashboard/create_team/$', views.TeamCreationView.as_view(), name='create-team'),
    url(r'^dashboard/toggle_lft/$', views.ToggleLFTView.as_view(), name='toggle-lft'),

    url(r'^dashboard/manage_team/$', views.CaptainHomeView.as_view(), name='manage-team'),
    url(r'^dashboard/manage_team/approve_member/(?P<participant_id>[0-9-_:]+)/$', views.ApproveMemberView.as_view(), name='approve-member'),
    url(r'^dashboard/manage_team/approve_captain/(?P<participant_id>[0-9-_:]+)/$', views.ApproveCaptainView.as_view(), name='approve-captain'),
    url(r'^dashboard/manage_team/disband/$', views.DisbandTeamView.as_view(), name='disband-team'),

    url(r'^archive/(?P<email_id>\d+)/$', views.ArchiveEmailView.as_view(), name='archive-email'),

)

# if settings.DEBUG:
#     urlpatterns += [
#         url(r'^403/$', 'signup.errors.error403', name='403'),
#         url(r'^404/$', 'signup.errors.error404', name='404'),
#         url(r'^500/$', 'signup.errors.error500', name='500'),
#     ]

base/models.py
from django.contrib.auth import models as auth_models
from django.db import models
from django.db.models.signals import post_save, pre_save, pre_delete
from django.dispatch import receiver

from base.utils import AUDIENCE_CHOICES


class GlobalSettings(models.Model):
    number_of_teams = models.IntegerField(default=40)
    administrator_bind_dn = models.CharField(max_length=100)
    administrator_bind_pw = models.CharField(max_length=100)
    check_in_date = models.DateTimeField(null=True)
    max_team_size = models.PositiveIntegerField(default=8)

    competition_name = models.CharField(max_length=100, blank=True, null=True)
    competition_date = models.DateTimeField(null=True)
    competition_prefix = models.CharField(max_length=15, blank=True, null=True)

    enable_account_creation = models.BooleanField(default=True)
    enable_red = models.BooleanField(default=True)
    enable_green = models.BooleanField(default=True)

    # Where are the docs?
    documentation_url = models.URLField(blank=True, null=True, max_length=200,
                                         help_text="Where blue teams can go to see their documentation. Usually a Google Drive folder.")
    green_docs_url = models.URLField(help_text="Where green team members can go to see their documentation. Usually a "
                                               "Google Drive folder.", null=True)
    red_docs_url = models.URLField(help_text="Where red team members can go to see their documentation. Usually a "
                                             "Google Drive folder.", null=True)

    certificate_template = models.FileField(null=True, blank=True)
    rules_version = models.CharField(max_length=40, null=True, blank=True)


class Team(models.Model):
    number = models.PositiveIntegerField(default=0)
    name = models.CharField(unique=True, max_length=50)
    looking_for_members = models.BooleanField(default=True, help_text="Allow anyone to join your team; uncheck if your team is full.")
    disbanded = models.BooleanField(default=False)

    def members(self):
        return Participant.objects.filter(team=self)

    def captains(self):
        return self.members().filter(captain=True)

    def requested_members(self):
        return Participant.objects.filter(requested_team=self)

    def requested_captains(self):
        return self.members().filter(requests_captain=True)

    def member_email_list(self):
        member_emails = []
        for member in self.members():
            member_emails.append(member.user.email)
        return member_emails

    def captain_names(self):
        names = []
        for captain in self.captains():
            name = captain.user.get_full_name()
            names.append(name)
        formatted = ', '.join(names)
        return formatted

    def captain_emails(self):
        emails = ''
        for captain in self.captains():
            if len(emails):
                emails += ', '
            emails = emails + captain.user.email
        return emails

    def is_full(self):
        from base import actions
        return len(self.members()) >= actions.get_global_setting('max_team_size')

    def __unicode__(self):
        return "Team {number}: {name}".format(number=self.number, name=self.name)

    class Meta:
        ordering = ['number']


class Participant(models.Model):
    user = models.OneToOneField(auth_models.User)
    team = models.ForeignKey('Team', blank=True, null=True)
    captain = models.BooleanField(default=False)
    requested_team = models.ForeignKey('Team', related_name='requested_team', blank=True, null=True)
    requests_captain = models.BooleanField(default=False)
    checked_in = models.BooleanField(default=False)
    looking_for_team = models.BooleanField(default=False, help_text='ISEAGE will put you on a team')

    # Only used for Red/Green
    is_red = models.BooleanField(default=False)
    is_green = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)

    @property
    def is_redgreen(self):
        return self.is_red or self.is_green

    def check_in(self):
        self.checked_in = True
        self.save(update_fields=['checked_in'])

    def undo_check_in(self):
        self.checked_in = False
        self.save(update_fields=['checked_in'])

    def user_is_captain(self):
        return self.captain or self.user.is_superuser

    def request_team(self, team):
        if not self.team and not self.is_redgreen:
            self.requested_team = team
            self.save(update_fields=['requested_team'])

    def request_promotion(self):
        if not self.requests_captain and not self.is_redgreen:
            self.requests_captain = True
            self.save(update_fields=['requests_captain'])

    def promote(self):
        if not self.captain and not self.is_redgreen:
            self.captain = True
            self.requests_captain = False
            self.save(update_fields=['captain', 'requests_captain'])

    def demote(self):
        if self.captain and not self.is_redgreen:
            self.captain = False
            self.save(update_fields=['captain'])

    def approve(self):
        """
        Approve a Red/Green Member

        Only applies to Red/Green
        """
        from base import actions
        if self.is_redgreen:
            self.approved = True
            self.save(update_fields=['approved'])
            actions.approve_user(self)

    def unapprove(self):
        """
        Unapprove a Red/Green Member

        Only applies to Red/Green
        """
        from base import actions
        if self.is_redgreen:
            self.approved = False
            self.save(update_fields=['approved'])
            actions.unapprove_user(self)

    def __unicode__(self):
        return "{username} ({name})".format(username=self.user.get_username(), name=self.user.get_full_name())

    class Meta:
        ordering = ['team']


class ArchivedEmail(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    audience = models.CharField(max_length=30, choices=AUDIENCE_CHOICES)
    send_time = models.DateTimeField(auto_now_add=True)

    sender = models.ForeignKey(auth_models.User)


########
# Signals
########
@receiver(post_save, sender=GlobalSettings)
def update_settings(sender, instance, **kwargs):
    from base import actions
    actions.reset_global_settings_object()


@receiver(post_save, sender=auth_models.User)
def create_participant(sender, instance, **kwargs):
    Participant.objects.get_or_create(user=instance)


@receiver(pre_save, sender=Participant)
def remove_old_ad_group(sender, instance, **kwargs):
    from base import actions
    fields = kwargs.get('update_fields', None)
    if fields:
        if not 'team' in fields:
            return

    try:
        current = Participant.objects.get(pk=instance.id)
    except Participant.DoesNotExist:
        return
    team = current.team
    if team:
        user_dn = actions.get_user_dn(instance.id)
        group_dn = actions.get_group_dn(team.id)
        actions.remove_user_from_group(user_dn, group_dn)


@receiver(post_save, sender=Participant)
def add_new_ad_group(sender, instance, **kwargs):
    from base import actions
    fields = kwargs.get('update_fields', None)
    if fields:
        if not 'team' in fields:
            return

    team = instance.team
    if team:
        user_dn = actions.get_user_dn(instance.id)
        group_dn = actions.get_group_dn(team.id)
        actions.add_user_to_group(user_dn, group_dn)


@receiver(pre_delete, sender=Team)
def remove_members(sender, instance, **kwargs):
    rc = instance.requested_captains()
    for member in rc:
        member.requests_captain = False
        member.save(update_fields=['requests_captain'])
    r = instance.requested_members()
    for participant in r:
        participant.requested_team = None
        participant.save(update_fields=['requested_team'])
    m = instance.members()
    for member in m:
        member.team = None
        member.captain = False
        member.save()

templates/approve_captain.html
{% extends "base.html" %}
{% load tt_web %}

{% block content %}
    <div class="row">
        <div class="col-md-11" style="max-width: 700px;">
            {% render_widget widget_data %}
                <p>Are you sure you want to promote {{ member.user.first_name }} {{ member.user.last_name }} to captain?</p>
                <form class='form-horizontal' action='' method="POST">
                    {% csrf_token %}
                    <input type="submit" action="{% url "approve-captain" member.id %}" class="btn btn-primary" value="Submit confirmation">
                </form>
            {% render_widget_bottom %}
        </div>
    </div>

{% endblock %}

templates/base.html
{% load tt_web %}
{% load cache %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ page_title }} - CDC Signup</title>
    <meta charset="UTF-8" />
    <link rel="icon" href="/static/img/favicon.ico" />

    <meta name="viewport" content="width=device-width, user-scalable=yes">

    <link rel="stylesheet" href="/static/includes/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="/static/includes/bootstrap-notify/css/bootstrap-notify.css" />
    <link rel="stylesheet" href="/static/includes/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/static/includes/bootstrap-datepicker/css/datepicker3.css" />
    <link rel="stylesheet" href="/static/styles/theme.css" />
    <link rel="stylesheet" href="/static/styles/style.css" />

    {% block head %}{% endblock %}
</head>

<body>

<div id="header">
    <div class="container-fluid">
        <div id="logo" class="row-fluid">
            <a href="{% url "site-index" %}">
                <div style="float: left;">
                    <img src="/static/img/ISEAGE.jpg"/>
                </div>
                <div>
                    <h1>CDC Signup</h1>
                </div>
            </a>
        </div>
    </div>
</div>

{% if messages %}
    {% for message in messages %}
        <div class="notifications top-center" {% if message.tags %}title="{{ message.tags }}"{% endif %} data-row="{{ message }}"></div>
    {% endfor %}
{% endif %}

<div id="content" style="min-height:1000px;">
    {% block full-content %} {# We use this block to override the whole content area, for error pages #}
    <div id="content-header">
        <h1>{{ page_title }}</h1>
        <div class="btn-group pull-right">
            {% if user.is_authenticated %}
                <div class="row-fluid" style="margin-bottom: 10px;">
                    <a class="btn btn-lg btn-primary" href="{% url "site-logout" %}">Logout</a>
                </div>
            {% endif %}
        </div>
    </div>
    <div id="breadcrumb">
        {% if not breadcrumbs %}<a href="/">Home</a>{% endif %}
        {{ breadcrumbs }}
        {% if user.is_authenticated %}
            <span class="pull-right" style="margin-top: 7px; margin-right: 20px;">Logged in as: <strong>{{ user }}</strong></span>
        {% endif %}
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="col-md-12">

                {% block content %}{% endblock %}

            </div>
        </div>
    </div>

    {% endblock %}
</div>

<script src="/static/includes/jquery-1.11.1.min.js"></script>
<script src="/static/includes/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/includes/bootstrap-notify/js/bootstrap-notify.js"></script>
<script src="/static/includes/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>

<script>
    $(document).ready(function(){
        //setup content height
        $(window).resize(function(){
            var new_height = $(window).height() - 55;
            if(new_height < 675) new_height = 675;
            $("#content").css('min-height', new_height);
        });

        $(window).trigger('resize');

        $('input.datepicker-input').datepicker({}).on('changeDate', function(ev) {
            $(this).datepicker('hide');
        });

        $('.notifications').each(function(){
            var that = $(this);
            var message = that.attr('data-row');
            var color = that.attr('title');
            var fade = { enabled: false };
            if (color == 'error') {
                color = 'danger';
            }
            else {
                fade = { enabled: true, delay: 4500 };
            }
            that.notify({
                message: {text: message},
                type: color,
                fadeOut: fade
            }).show();
        });
    });

</script>

{% block js %}{% endblock %}

</body>
</html>

templates/disband.html
{% extends "base.html" %}
{% load tt_web %}

{% block content %}
    <div class="row">
        <div class="col-md-11" style="max-width: 700px;">
            {% render_widget widget_data %}
                <strong>WARNING: This action is irreversible.</strong>
                <p>Are you sure you want to disband {{ team.name }}?</p>
                <form class='form-horizontal' action='' method="POST">
                    {% csrf_token %}
                    <input type="submit" action="{% url "step-down" %}" class="btn btn-danger" value="Disband team">
                </form>
            {% render_widget_bottom %}
        </div>
    </div>

{% endblock %}

templates/email_view.html
{% extends "base.html" %}
{% load tt_web %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">Subject: {{ archived.subject }}</h2>
                </div>
                <div class="panel-body">
                    {{ archived.content|linebreaks }}
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">Email Details</h2>
                </div>
                <table class="table">
                    {% if user.is_staff or user.is_superuser %}
                    <tr>
                        <th>Sender</th>
                        <td>{{ archived.sender.get_full_name }}</td>
                    </tr>
                    <tr>
                        <th>Audience</th>
                        <td>{{ archived.get_audience_display }}</td>
                    </tr>
                    {% endif %}
                    <tr>
                        <th>Sent At</th>
                        <td>{{ archived.send_time }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/forgot.html
{% extends "base.html" %}
{% load tt_web %}

{% block content %}

    <div class="col-md-6">
        <form class='form-horizontal' action='' method="POST">
            {% csrf_token %}
            {% render_form_widget form icon="fa-edit" %}
        </form>
    </div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="col-md-4">
    {% if blue_enabled %}
        <a class="btn btn-info btn-lg btn-block" href="{% url "signup" %}">Blue Team Signup</a>
    {% endif %}
    {% if red_enabled %}
        <a class="btn btn-danger btn-lg btn-block" href="{% url "red_signup" %}">Red Team Signup</a>
    {% endif %}
    {% if green_enabled %}
        <a class="btn btn-lg btn-success btn-block" href="{% url "green_signup" %}">Green Team Signup</a>
    {% endif %}
        <a class="btn btn-primary btn-lg btn-block" href="{% url "site-login" %}">Sign in</a>
    </div>
{% endblock %}

templates/join_team.html
{% extends "base.html" %}
{% load tt_web %}

{% block content %}
    <div class="row">
        <div class="col-md-11" style="max-width: 700px;">
            {% render_widget widget_data %}
                <p>Are you sure you want to join {{ team.name }}?</p>
                <form class='form-horizontal' action='' method="POST">
                    {% csrf_token %}
                    <input type="submit" action="{% url "join-team" team.id %}" class="btn btn-primary" value="Submit request">
                </form>
            {% render_widget_bottom %}
        </div>
    </div>

{% endblock %}

templates/leave_team.html
{% extends "base.html" %}
{% load tt_web %}

{% block content %}
    <div class="row">
        <div class="col-md-11" style="max-width: 700px;">
            {% render_widget widget_data %}
                <p>Are you sure you want to leave {{ team.name }}?</p>
                <form class='form-horizontal' action='' method="POST">
                    {% csrf_token %}
                    <input type="submit" action="{% url "leave-team" %}" class="btn btn-danger" value="Leave team">
                </form>
            {% render_widget_bottom %}
        </div>
    </div>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}

    <div class="row-fluid">
        <div class="col-md-6 col-md-offset3">
            <div class="widget-box">
                <div class="widget-title">
                    <h5>Login</h5>
                </div>
                <div class="widget-content">
                    {% if form.errors %}
                    <div class="alert alert-error" style="text-align: center; margin-top: -15px;">Invalid credentials. &nbsp;Please try again.</div>
                    {% endif %}

                    <form class="login-form form-horizontal" method="POST">
                        {% csrf_token %}

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">Username</label>
                            <div class="col-sm-4">
                                <div class="input-group">
                                    {{ form.username }}
                                    <span class="input-group-addon" style="padding-left: 8px;">@iseage.org</span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">Password</label>
                            <div class="col-sm-4" style="margin-bottom: 10px;">
                                {{ form.password }}
                            </div>
                            <div class="col-sm-4">
                                <a href="{% url "forgot-password" %}">Forgot your password?</a>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-6 col-sm-offset-5">
                                <input class="btn btn-primary" type="submit" value="Login" style="margin-bottom: 15px;"/>
                            </div>
                        </div>
                        <input type="hidden" name="next" value="{{ next }}" />

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}

    <script>
        $(document).ready(function(){
            $('#id_username').focus();
        });
    </script>

{% endblock %}

templates/red_green_signup.html
{% extends "base.html" %}
{% load tt_web %}

{% block content %}
{{ form.non_field_errors }}
    <div class="col-md-6">
        <form class="form-horizontal" action='' method="POST" id="simple-form" enctype="multipart/form-data">
            {% csrf_token %}
            {% render_form_widget form icon="fa-sliders" %}
        </form>
    </div>

{% endblock %}

templates/request_captain.html
{% extends "base.html" %}
{% load tt_web %}

{% block content %}
    <div class="row">
        <div class="col-md-11" style="max-width: 700px;">
            {% render_widget widget_data %}
                <p>Are you sure you want to request to become a captain of {{ team.name }}?</p>
                <form class='form-horizontal' action='' method="POST">
                    {% csrf_token %}
                    <input type="submit" action="{% url "request-promotion" %}" class="btn btn-primary" value="Submit request">
                </form>
            {% render_widget_bottom %}
        </div>
    </div>

{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load tt_web %}

{% block content %}

    <div class="col-md-11">
        <form class='form-horizontal' action='' method="POST">
            {% csrf_token %}
            {% render_form_widget form icon="fa-edit" %}
        </form>
    </div>

{% endblock %}

templates/step_down.html
{% extends "base.html" %}
{% load tt_web %}

{% block content %}
    <div class="row">
        <div class="col-md-11" style="max-width: 700px;">
            {% render_widget widget_data %}
                <p>Are you sure you want to step down as a captain of {{ team.name }}?</p>
                <form class='form-horizontal' action='' method="POST">
                    {% csrf_token %}
                    <input type="submit" action="{% url "step-down" %}" class="btn btn-danger" value="Step down">
                </form>
            {% render_widget_bottom %}
        </div>
    </div>

{% endblock %}

templates/team_list.html
{% extends "base.html" %}
{% load tt_web %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if teams %}
                <div class="table-responsive">
                    <table class="table table-striped" id="current-teams">
                        <caption>Select a Team</caption>
                        <thead><tr>
                            <th>Name</th>
                            <th>Members</th>
                            <th>Captains</th>
                            <th>Captain Emails</th>
                            <th>Looking for New Members</th>
                            <th>Actions</th>
                        </tr></thead>
                        <tbody>
                        {% for team in teams %}
                        <tr id="team-{{ team.id }}">
                            <td class="name">{{ team.name }}</td>
                            <td class="count">{{ team.member_count }}</td>
                            <td class="captains">{{ team.captain_names }}</td>
                            <td class="captain-emails">{{ team.captain_emails }}</td>
                            <td class="looking-for-members">{{ team.looking_for_members|yesno:"Yes,No" }}</td>
                            <td>
                                <a class="btn btn-primary" href="{% url "join-team" team.id %}">Request to join</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
             {% else %}
                <p>It looks like there aren't any teams yet. If you want, you can <a href="{% url "create-team" %}">make a new one yourself</a>.</p>
            {% endif %}
        </div>
    </div>

{% endblock %}